baseURL = "https://www.yitaohe.com/"
locale = "zh-cn"
title = "yitaohe.com"
defaultContentLanguage = "en"

[params]
  turnstileSiteKey = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  overview = "/overview/"
  blogs = "/blogs/:sections[1]/:slug/"
  comments = "/comments/"

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[languages.zh]
  contentDir = "content/zh"
  hasCJKLanguage = true
  locale = "zh-cn"
  weight = 1
  label = "中文"
  title = "yitaohe.com"

[languages.en]
  contentDir = "content/en"
  locale = "en"
  weight = 2
  label = "English"
  title = "yitaohe.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
